version: 3

shopt: [globstar]

tasks:
  default:
    deps: [lint-with-markdownlint, lint-with-jsonschema-cli]
  
  lint-with-markdownlint:
    cmds:
      - markdownlint **/*.md
  
  lint-with-jsonschema-cli:
    cmds:
      - jsonschema-cli -h
