name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  lint-with-jsonschema-cli:
    name: Lint with `jsonschema-cli`
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip3 install jsonschema-cli
          for directory in */; do
            env -C "$directory" jsonschema-cli validate "../theme.json" "theme.yaml"
          done
          